### ISSUE TITLE
BankNotes Plugin

### ISSUE THREAD

**Issue by ghost** [Gamecube762/BankNote#1]
Is this plugin abandoned? I was wondering if I could modify it, or take the plugin and start making it better if I could. Thanks!

**Comment by Gamecube762** [comment]
I wouldn't considered the plugin abandoned, more as "Complete". As I see it, currently there is no problems(that I'm aware of) or a need update it.

Feel free to use it, modify it, and change it how you see fit. All I request is credit for the original plugin/code.

Also feel free to ask any questions you have!

**Comment by ghost** [comment]
Thanks! I just would like to make it more configurable. (Messages, etc) I will make sure to give you original credit! :)
